{% set name = "topoflow-erode-d8-global-csdms" %}
{% set version = "3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/topoflow-bridge

requirements:
  build:
    - bmi-babel
    - topoflow
  run:
    - bmi-babel
    - topoflow

test:
  requires:
    - pymt
    - bmi-tester

about:
  home: http://csdms.colorado.edu/wiki/Model_help:Erode
  license: Apache
  summary: Erode, a TopoFlow component, is a raster-based, fluvial landscape
